import { useEffect, useRef, useState, type MutableRefObject } from 'react'
import type { ExploitTag, PlayerProfile, PrimaryTag, StatSnapshot } from '../../shared/types'

const show=(v:number|null)=>v??'–', parse=(v:string)=>v.trim()===''?null:Number(v)
export default function PlayerView({player,setPlayer,flushRef}:{player:PlayerProfile,setPlayer:(p:PlayerProfile)=>void,flushRef:MutableRefObject<()=>Promise<void>>}){
  const [editing,setEditing]=useState(false),[values,setValues]=useState(['','','']),[error,setError]=useState(''),[notes,setNotes]=useState(player.notes),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState(''),[tags,setTags]=useState<ExploitTag[]>([]),[primaryTags,setPrimaryTags]=useState<PrimaryTag[]>([]),[history,setHistory]=useState<StatSnapshot[]>([]),[addingTag,setAddingTag]=useState(false),[tagName,setTagName]=useState(''),[tagDescription,setTagDescription]=useState('')
  const timer=useRef<ReturnType<typeof setTimeout>|null>(null), row=useRef<HTMLDivElement>(null)
  const saveNotes=async()=>{if(timer.current)clearTimeout(timer.current);if(notes===player.notes)return;setSaving(true);try{await window.pokerNotes.updateNotes(player.id,notes);player.notes=notes;setSaveError('')}catch{setSaveError('Notes not saved — retrying')}finally{setSaving(false)}}
  flushRef.current=saveNotes
  useEffect(()=>{window.pokerNotes.getExploitTags().then(setTags);window.pokerNotes.getPrimaryTags().then(setPrimaryTags);window.pokerNotes.getStatHistory(player.id).then(setHistory);return()=>{if(timer.current)clearTimeout(timer.current)}},[player.id])
  const edit=(index:number)=>{const s=player.latestStats;setValues([s?.hands,s?.vpip,s?.pfr].map(v=>v==null?'':String(v)));setEditing(true);setTimeout(()=>row.current?.querySelectorAll('input')[index].focus())}
  const commit=async()=>{const [hands,vpip,pfr]=values.map(parse);if((hands!==null&&(!Number.isInteger(hands)||hands<0))||[vpip,pfr].some(v=>v!==null&&(Number.isNaN(v)||v<0||v>100))){setError('Hands must be a non-negative integer; VPIP/PFR must be 0–100.');return}try{const latest=await window.pokerNotes.commitStats(player.id,{hands,vpip,pfr});setPlayer({...player,latestStats:latest});setHistory([latest,...history].slice(0,10));setEditing(false);setError('')}catch{setError('Stats not saved. Try again.')}}
  const primary=async(key:string)=>{const value=player.primaryClassification===key?null:key;await window.pokerNotes.setPrimaryClassification(player.id,value);setPlayer({...player,primaryClassification:value})}
  const toggle=async(tag:ExploitTag)=>{await window.pokerNotes.toggleExploitTag(player.id,tag.id);const selected=player.exploitTags.some(t=>t.id===tag.id);setPlayer({...player,exploitTags:selected?player.exploitTags.filter(t=>t.id!==tag.id):[{...tag,selectedAt:new Date().toISOString()},...player.exploitTags]})}
  const orderedPrimary=[...primaryTags].sort((a,b)=>Number(b.key===player.primaryClassification)-Number(a.key===player.primaryClassification))
  const selectedIds=new Set(player.exploitTags.map(t=>t.id)),unselectedTags=tags.filter(tag=>!selectedIds.has(tag.id))
  const addTag=async()=>{try{const tag=await window.pokerNotes.createExploitTag(tagName,tagDescription);await window.pokerNotes.toggleExploitTag(player.id,tag.id);setTags([...tags,tag]);setPlayer({...player,exploitTags:[tag,...player.exploitTags]});setTagName('');setTagDescription('');setAddingTag(false);setError('')}catch(e){setError(String(e))}}
  return <section className="player"><h1>{player.username}</h1><div ref={row} className="stats" onBlur={e=>{if(!row.current?.contains(e.relatedTarget as Node))commit()}}>{editing?values.map((v,i)=><span key={i}><input aria-label={['Hands','VPIP','PFR'][i]} className={error?'invalid':''} value={v} onChange={e=>setValues(values.map((x,j)=>j===i?e.target.value:x))} onKeyDown={e=>e.key==='Enter'&&commit()}/>{i<2&&' | '}</span>):[player.latestStats?.hands,player.latestStats?.vpip,player.latestStats?.pfr].map((v,i)=><span key={i} title={history.map(h=>`${show([h.hands,h.vpip,h.pfr][i] ?? null)}${i?' @ '+show(h.hands)+' hands':''} — ${new Date(h.recordedAt).toLocaleDateString()}`).join('\n')} onClick={()=>edit(i)}>{show(v ?? null)}{i<2&&' | '}</span>)}</div>{error&&<p className="error">{error}</p>}<time>{player.latestStats?`Updated ${new Date(player.latestStats.recordedAt).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}`:'No stats yet'}</time>
  <div className="strip">{orderedPrimary.map(tag=><button key={tag.key} title={tag.description} style={player.primaryClassification===tag.key?{backgroundColor:tag.color,borderColor:tag.color}:undefined} className={player.primaryClassification===tag.key?'active':''} onClick={()=>primary(tag.key)}>{tag.name}</button>)}</div>
  {player.exploitTags.length>0&&<div className="enabled-exploits">{player.exploitTags.map(tag=><button key={tag.id} title={tag.description} style={{backgroundColor:tag.color,borderColor:tag.color}} className="active" onClick={()=>toggle(tag)}>{tag.name}</button>)}</div>}
  <div className="strip exploit-options">{unselectedTags.map(tag=><button key={tag.id} title={tag.description} style={{borderColor:tag.color}} onClick={()=>toggle(tag)}>{tag.name}</button>)}</div>
  {addingTag?<div className="tag-form"><input aria-label="Custom tag name" placeholder="Tag name" value={tagName} onChange={e=>setTagName(e.target.value)}/><input aria-label="Custom tag description" placeholder="What should you do differently?" value={tagDescription} onChange={e=>setTagDescription(e.target.value)}/><button onClick={addTag}>Add</button><button onClick={()=>setAddingTag(false)}>Cancel</button></div>:<button className="add-tag" onClick={()=>setAddingTag(true)}>+ Custom exploit</button>}
  <textarea aria-label="Player notes" value={notes} placeholder="Add reads and observations..." onChange={e=>{setNotes(e.target.value);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(saveNotes,450)}} onBlur={saveNotes}/>{(saving||saveError)&&<p className={saveError?'error':'status'}>{saveError||'Saving…'}</p>}</section>
}
